spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/certs
          cache-time-to-live: 5s
      client:
        registration:
          keycloak:
            name: spring-keycloak
            client-id: spring-service
            client-secret: ZPVLOEBjY9S13zUMpecLhi4u0uGhxuCw
            redirect-uri: http://localhost:7000/auth/api/v1/auth/login
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-keycloak
            authorization-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/userinfo

auth:
  authorization-code-redirect-uri: http://localhost:7000/auth/api/v1/auth/access-token
  logout-redirect-uri: http://localhost:7000/auth/api/v1/auth/logout

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka