spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-service
            redirect-uri: http://localhost:7000/auth/api/v1/auth/login
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-keycloak
            authorization-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/spring-keycloak/protocol/openid-connect/userinfo

  config:
    import: optional:http://localhost:7001/
    fail-fast: true
    enabled: true